name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        pandoc:
          - edge
          - latest
    env:
      DEBIAN_FRONTEND: noninteractive

    container:
      image: pandoc/core:${{ matrix.pandoc }}-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add lua5.4-busted make

      - name: Test
        run: make test BUSTED=busted-5.4
